# Generated by Django 4.0.4 on 2022-06-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
