# Generated by Django 4.0.4 on 2022-06-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
